version: '3'
services:
  node:
    image: my-app
    build: .
    networks:
      - backend
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./logs:/logs
      - ./src:/src
    environment:
      - PORT=${PORT}
    restart: 'on-failure'
  postgres:
    image: my-db
    build: ./database/
    networks:
      - backend
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./database/initdb:/initdb
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: 'on-failure'
networks:
  backend:
    name: backend
    driver: bridge
