version: '3'
services:
  node:
    image: nest-app
    build: .
    networks:
      - backend
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
      - ./${STATIC_FILE_FOLDER}:/app/${STATIC_FILE_FOLDER}
    env_file: docker.env
    restart: always
    links:
      - postgres
  postgres:
    image: postgres-db
    build: ./database/
    networks:
      - backend
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - db-data:${PGDATA}
      - db-logs:/var/log/postgresql
    env_file: docker.env
    restart: always
networks:
  backend:
    name: backend
    driver: bridge
volumes:
  db-logs:
  db-data:
