version: '3'
services:
  node:
    image: nest-app
    build: .
    networks:
      - backend
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
    environment:
      - PORT=${PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - USE_FASTIFY=${USE_FASTIFY}
      - DATABASE_URL=${DATABASE_URL}
    restart: always
    links:
      - postgres
  postgres:
    image: postgres-db
    build: ./database/
    networks:
      - backend
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - db-data:${PGDATA}
      - db-logs:/var/log/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${PGPORT}
      - PGDATA=${PGDATA}
    restart: always
networks:
  backend:
    name: backend
    driver: bridge
volumes:
  db-logs:
  db-data:
